version: '3.8'

services:
  # Banco de Dados (PostgreSQL)
  db:
    image: postgres:15
    container_name: cinedata_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cinedata_imdb
    ports:
      - "5433:5432"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  # Serviço de Processamento de Dados (Python + Pandas)
  data-service:
    build: ./data-service
    container_name: cinedata_python
    volumes:
      - ./data-service:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://victorhugo-neo:123@db:5432/cinedata_imdb

  # Backend da Aplicação (Node.js + TypeScript)
  backend:
    build: ./backend
    container_name: cinedata_node
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - data-service

  # Frontend (React + TypeScript)
  frontend:
    build: ./frontend
    container_name: cinedata_react
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true